version: '3'
services:

  flaskapp:
    build:
      context: backend-flask
      dockerfile: Dockerfile
    image: achebeh/aws-cruddur-2023-flaskapp
    container_name: flask-app
    volumes:
      - /backend-flask:/backend-flask
    environment:
      FRONTEND_URL: "https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      OTEL_SERVICE_NAME: "backend-flask"
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://api.honeycomb.io/"
      OTEL_EXPORTER_OTLP_HEADERS: "x-honeycomb-team=${HONEYCOMB_API_KEY}"
    ports:
      - "4567:4567"
    networks:
      - cruddur
    healthcheck:
      test: curl --fail https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST} || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 0s

  webapp:
    depends_on:
      - flaskapp
    build:
      context: frontend-react-js
      dockerfile: Dockerfile
    image: achebeh/aws-cruddur-2023-webapp
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - /frontend-react-js:/frontend-react-js
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    networks:
      - cruddur

networks: 
  cruddur: