version: '3.8'
services:
  frontend:
    build:
      context: ./frontend-react-js
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend-react-js:/app
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    build:
      context: ./backend-flask
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend-flask:/app
    env_file:
      - .env
    
    # depends_on:
    #   - frontend

